### PR TITLE
Rt project notes

### PR DESCRIPTION
**Pull request by rtravitz**
@notmarkmiranda, @s-espinosa Here's a pass at adding notes to the project.

#### The user can add a note when creating a new project:
screen shot 2017-02-14 at 1 29 27 pm

#### Admins can see notes on the current projects section of their panel (demo night show page):
screen shot 2017-02-14 at 1 22 20 pm

#### No users can see the notes:
screen shot 2017-02-14 at 1 23 04 pm

The owner can edit their note on the normal project edit form!

### CODE REVIEW

**Comment by s-espinosa** [comment]
@rtravitz Mark and I are thinking that maybe we can adjust the table so that we only have single letters above the table for 'representation', 'challenge,' and 'wow.' Then we can make them smaller. Thoughts?

**Comment by rtravitz** [comment]
@s-espinosa that sounds good. I will make that change and check out the column spacing.

**Comment by rtravitz** [comment]
screen shot 2017-03-26 at 10 25 53 pm

@s-espinosa Here's the update. In addition to changing the representation, challenge, and wow headers, I also changed the column size down for the first three intro categories. They seemed to be taking up a lot of space unnecessarily. Sorry I fell off the wagon on this PR!

**Comment by notmarkmiranda** [comment]
@rtravitz with the :fire: did you guys know you can do slack type emojis in github comments? :yes: :aw_yeah:

**Comment by s-espinosa** [comment]
@rtravitz I like it! Also, my closing and opening was just me playing with Waffle to see if something would work and in no way an attempt to get you to look at this.

@notmarkmiranda Any hesitation about merging?

**Comment by notmarkmiranda** [comment]
@s-espinosa no hesitation, but if it breaks production, @rtravitz has to fix it

**Comment by notmarkmiranda** [comment]
sorry everyone. clicked close and comment instead of just comment.

**Pull request merged**
